const ADMIN_PAGE = 0;
const ALERT_PAGE = 1;
const TCP_PAGE = 2;
const GRAPHITE_PAGE = 3;
const NOTIFIER_PAGE = 4;
const TEMPLATE_PAGE = 5;

const STYLE_DANGER = "danger";
const STYLE_DEFAULT = "default";
const STYLE_INFO = "info";
const STYLE_PRIMARY = "primary";
const STYLE_SUCCESS = "success";
const STYLE_WARN = "warning";

const SIZE_DEFAULT = "";
const SIZE_EX_SMALL = "xs";
const SIZE_LARGE = "lg";
const SIZE_PILL = "pill";
const SIZE_SMALL = "sm";
const SIZE_THICK = "thick";

const ACTION_OPEN_CONTENT = "openContent";
const ACTION_SWITCH_ALERT = "switchAlert";
const ACTION_FETCH_ALERT_DATA = "fetchAlertData";
const ACTION_OPEN_GRAPHITE_MODAL = "openGraphiteModal";
const ACTION_CLOSE_GRAPHITE_MODAL = "closeGraphiteModal";
const ACTION_FETCH_GRAPHITE_DATA = "fetchGraphiteData";

const ACTION_OPEN_TCP_MODAL = "openTCPModal";
const ACTION_CLOSE_TCP_MODAL = "closeTCPModal";
const ACTION_FETCH_TCP_DATA = "fetchTCPData";

const ACTION_OPEN_TEMPLATE_MODAL = "openTemplateModal";
const ACTION_CLOSE_TEMPLATE_MODAL = "closeTemplateModal";
const ACTION_FETCH_TEMPLATE_DATA = "fetchTemplateData";

const MODE_ADD = "modalAdd";
const MODE_UPDATE = "modalUpdate";
const MODE_DELETE = "modalDelete";

export {ADMIN_PAGE, ALERT_PAGE, TCP_PAGE, GRAPHITE_PAGE, NOTIFIER_PAGE, TEMPLATE_PAGE,
STYLE_DANGER, STYLE_DEFAULT, STYLE_INFO, STYLE_PRIMARY, STYLE_SUCCESS, STYLE_WARN,
  SIZE_DEFAULT, SIZE_EX_SMALL, SIZE_LARGE, SIZE_PILL, SIZE_SMALL, SIZE_THICK,
ACTION_OPEN_CONTENT, ACTION_SWITCH_ALERT, ACTION_FETCH_ALERT_DATA,
ACTION_OPEN_GRAPHITE_MODAL, ACTION_CLOSE_GRAPHITE_MODAL, ACTION_FETCH_GRAPHITE_DATA,
ACTION_OPEN_TCP_MODAL, ACTION_CLOSE_TCP_MODAL, ACTION_FETCH_TCP_DATA,
ACTION_OPEN_TEMPLATE_MODAL, ACTION_CLOSE_TEMPLATE_MODAL, ACTION_FETCH_TEMPLATE_DATA,
MODE_ADD, MODE_UPDATE, MODE_DELETE,
};