const metrics = [
  {
    "description": "User state CPU usage",
    "formula": "averageSeriesWithWildcards($node.cpu.*.percent.user, 2)",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["CPU"],
  },
  {
    "description": "System state CPU usage",
    "formula": "averageSeriesWithWildcards($node.cpu.*.percent.system, 2)",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["CPU"],
  },
  {
    "description": "CPU load(Long term)",
    "formula": "$node.load.load.relative.longterm",
    "range": "[0, INF)",
    "unit": "",
    "categories": ["CPU"],
  },
  {
    "description": "CPU load(Short term)",
    "formula": "$node.load.load.relative.shortterm",
    "range": "[0, INF)",
    "unit": "",
    "categories": ["CPU"],
  },
  {
    "description": "Memory usage",
    "formula": "$node.memory.percent.used",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["RAM", "Physical"],
  },
  {
    "description": "Swap usage",
    "formula": "$node.swap.percent.used",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["RAM", "Swap"],
  },
  {
    "description": "Network interface eth0 receive rate",
    "formula": "$node.interface.eth0.if_octets.rx",
    "range": "[0, INF)",
    "unit": "B/min",
    "categories": ["Network", "IO"],
  },
  {
    "description": "Network interface eth0 send rate",
    "formula": "$node.interface.eth0.if_octets.tx",
    "range": "[0, INF)",
    "unit": "B/min",
    "categories": ["Network", "IO"],
  },
  {
    "description": "I/O utils of /dev/xvda1",
    "formula": "asPercent($node.disk.dev_xvda1.disk_io_time.io_time, 1000)",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["Disk", "IO"],
  },
  {
    "description": "I/O utils of /dev/xvdb1",
    "formula": "asPercent($node.disk.dev_xvdb1.disk_io_time.io_time, 1000)",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["Disk", "IO"],
  },
  {
    "description": "File descriptors used",
    "formula": "$node.fhcount.file_handles.used",
    "range": "[0, INF)",
    "unit": "",
    "categories": ["File System"],
  },
  {
    "description": "Root partition used",
    "formula": "$node.df.root.percent_bytes.used",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["File System"],
  },
  {
    "description": "Data partition used",
    "formula": "$node.df.data.percent_bytes.used",
    "range": "[0, 100]",
    "unit": "%",
    "categories": ["File System"],
  },
];

export default metrics;